### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by bhuvak** [NuGet/NuGetGallery#1156]
### Dev to QA:
- [x]  Unit tests are added for the new feature and are passing in Team city. 
- [x] All changes from the "dev" branch that are to be merged to QA is linked to a git hub issue.  
- [x] Share the iteration test plan to the team. For each new feature, explicitly call out the relevant tracking work item and changesets,DB migrations,related ops changes and new configuration settings, if any.
### Signing off in QA:
- [x] Run functional tests right after deployment to QA and make sure they pass.
- [x] Run the migration related testing before running the migrations (new code against old DB).  
- [x] The test plan relevant to the current iteration is executed ( all p0, p1 and p2).
- [x] All open issues that came during testing of new features are fixed in "QA" branch. For issues which are not fixed, tracking git hub issues are logged in backlog.
- [x] p0 functional automation added for new features and the new tests are passing.
- [x] All the p0 tests in the newly added features are tested in at least two different browsers (chrome and IE).
- [x] All end to end scenarios in our "End to End tests/Regression Suite" are verified[most of them would be covered by the functional automation run].
- [x] Client Compat tests are validated in QA.
### Signing off in Staging:
- [x] Functional automation, migration testing and p0 tests for new features should be working fine.
#### Pre-Deployment:
- [x] Create new passwords and update the environment configuration files as required.
- [x] Check all the settings in cscfg are pointing to the right values and make sure any new config setting is added to the production configuration.
- [x] Make sure that the background tasks related to ops (one off tasks like scripts to remove duplicates, lower casing blob names) were run on production.
- [x] Make sure that any deployment to be done to the production Ops (relevant to the current change) is being done.
- [x] Do a DB backup.
#### Deployment:
- [x] Deploy in staging slot with the cscfg file having updated passwords.
- [x] Run the E2E tests and the tests for the new features that are part of current deployment.
- [x] Run the Migrations.
- [x] VIP swap.
- [x] Run the tests on production slot.
#### Post-Deployment:
- [x] Update the passwords used by worker role as well.
- [x] Regenerate old storage keys and remove old site user from database.
- [x] Update the "staging" slot in production to the latest code and latest cscfg.
- [x] Update the cscfg files in sharepoint too.
