### ISSUE TITLE
7/8/2013 Production Deployment Checklist

### ISSUE THREAD

**Issue by claycompton** [NuGet/NuGetGallery#1299]
Dev to QA:
- [x] Create and share the iteration test plan for the team. For each new feature, explicitly call out the relevant tracking work item and changesets,DB migrations,related ops changes and new configuration settings, if any. 

Signing off in QA:
- [x] Run functional tests. 
- [x] Run the migration-related testing and then do migrations (new code against old DB) (if needed).
- [x] The test plan relevant to the current iteration is executed ( all p0, p1 and p2). 
- [x] All bugs are either fixed or have GitHub issues tracking them. 
- [x] p0 functional automation is defined for new features. 

Signing off in Staging:
- [x] Re-run functional automation
- [x] Re-run any migration-related testing and do migrations (if needed)

Deployment:
- [x] Follow the directions for Blob Accounts and Database in onenote:///\clayco5\NuGetNotes\Nuget%20Gallery\Deployment.one#Steps%20to%20deploy%20and%20update%20passwords%20(in%20Antares)
- [x] Make sure that any deployment or one-off tasks to be done to the production Ops are done.
