### ISSUE TITLE
Deploy D4 to Production

### ISSUE THREAD

**Issue by analogrelay** [NuGet/NuGetGallery#2118]
# Deployment D4

**Status**: Testing Complete.

**Focus**: Fix $skipToken issue and other Gallery contributions/UI tweaks.

**Services to Deploy**: 
- V2Gallery - v3.0.33 - https://nugetbuild.cloudapp.net/viewLog.html?buildId=2448&tab=buildResultsDiv&buildTypeId=Gallery_Application_Master

**Bugs Fixed**: https://github.com/NuGet/NuGetGallery/issues?milestone=53&page=1&state=closed
## Deployment Process
- [ ] Deploy relevant version of the V2 Gallery Service using Octopus
- [ ] After Production Deployment ONLY: Close this bug!
## Pull Requests/Interesting Commits

See the **Bugs Fixed** section for details.
## Test Plan

Since the $skiptoken bug fix has code change in the mainline path ,it would be good to make sure that paging works fine in all the below scenarios with this change. 

Search endpoint : 
- [ ] External Search end point.
- [ ] In-built lucene index in the web server.
- [ ] Query run against Database (in case if Lucene cannot interpret the sort order or some thing) how to simulate this scenario?

Clients:
All these end-points, need to be tested from all clients :
- [x] NuGet Add package dialog.
- [x] NuGet package manager console. (Get-package –ListAvailable  with filter option)
- [x] NuGet command line
- [x] Web matrix
- [ ] Direct Odata feed query.
- [x] Search query from web browser and paging through results.
- [ ] Linqpad
- [ ] API based simple client
- [ ] Searching against curated feeds (web matrix, windows 8 and .net curated feed) for sanity.

Other bug fixes:
- [ ] Enlist on gallery code using localized OS and run Enable-LocalTestMe.ps1, verify F5 works - issue #1950 
- [x] Verify the search box border thickness in IE, Chrome and Firefox at different zoom - issue #2029
- [x] Ran build on galops and then run galops.exe, make sure no exception is thrown - issue #2096 
- [x] Verify the octopus deployment mention on the footer - issue #2087
- [x] Double check the .cscfg files in source and compare with settings in Azure - issue #2094
- [x] Verify the links after logging in as Admin, click on any of the following - issue #1482, issue #2079  
  - [x] The link to your account in the header,
  - [x] The "Contact Us" link in the footer, or
  - [x] The "Terms of Use" or "Privacy Policy" links in the footer.
  - [x] The configuration link
- [ ] Verify the stats total on the home page is shown correctly. Host the gallery in IIS under a virtual directory such as "NuGet/V2". Verify the stats is still shown - issue #818 
- [x] Log in, go to Manage My Packages page, verify the following - issue #224 
  - [x] No more typo in "totalDownload"
  - [x] If only one package is display render "You have one package." in the table footer
  - [x] If more then one "You have a total of {0} packages."
  - [x] If the user has only unlisted packages the listed table will now not be rendered. Instead it just shows "You don't have any packages here." 
- [x] Run gallery functional tests
## Test Status
1. Int Deployment is complete. 
2. Testing in progress.
