### ISSUE TITLE
Deploy D5 to Production

### ISSUE THREAD

**Issue by analogrelay** [NuGet/NuGetGallery#2153]
# Deployment D5

**Status**: Testing Complete.

**Focus**: Add Copy Database and Metadata Event Stream jobs and fix some work service issues

**Services to Deploy**: 
- Work - **3.0.31**
  actual - **3.0.34-01**

**Bugs Fixed**: https://github.com/NuGet/NuGetGallery/issues?milestone=54&page=1&state=closed
## Deployment Process
- [x] Deploy the Work Service Database (see @anurse - this has been done in int but will **need to be done before deploying to prod**)
- [x] Deploy the Work Service Package
- [x] Run the "_env_-schedule.ps1" script in the Scripts folder of the Deployment Repository
## Pull Requests/Interesting Commits

See the **Bugs Fixed** section for details.
## Test Plan
- [x] Work Service can double-dequeue! #2151 
  - [x] make sure the database backups are being created and not flooding the server with "copytemp_" databases
- [x] Use Azure SQL Rest APIs for Copying/Cleaning Databases #2144: 
  - [x] make sure the legacy databases are backed-up and that backups are cleaned up successfully. 
  - [x] Also, keep an eye on Export/Import jobs 
- [x] Client Version Download Report stops at 2.7 #2143 
  - [x] verify the NuGet Client Usage table on the statistics page 
- [x] Package Statistics in Warehouse is incorrect #2152 
## Test Status
1. Test is complete.
2. Deployed to production.
