### ISSUE TITLE
Deploy D8 to Production

### ISSUE THREAD

**Issue by analogrelay** [NuGet/NuGetGallery#2189]
# Deployment D8

**Status**: Testing complete.

**Focus**: Gallery Bug Fixes

**Services to Deploy**: 
- Gallery - v3.0.70-r-master

**Bugs Fixed**: https://github.com/NuGet/NuGetGallery/issues?milestone=57&page=1&state=closed
## Deployment Process
- [x] Promote V2 Gallery Service
## Test Plan
- [x] Verify that during the upload process, the button is disabled after being clicked once - issue #430 - Dan
  - make sure the Upload button cannot be double-clicked
- [x] Verify the Search button accessibility - issue #1187 - Zhi
  - start the home page, right click View Source and verify the submit button has a value of Submit
- [x] Verify the validation fields/layout for Register, SignIn, EditMetadata, Contact Support, Account, VerifyPackage (Package Upload) pages for the following browsers - issue #1314 - Dan
  - IE, FF, Chrome, Opera, Safari
- [x] Verify that hitting Enter in icon url field in Edit Package page will not save the edits - #1497 - Dan
  - Basically when user press enter while the focus is inside a box, the edit package form will not be submitted.
- [x] Verify there is an About page added to the gallery about contributors and contributions, basically a change log - #1589 - Zhi
- [x] Verify the text on Delete Package page - #1877 - Zhi
- [x] Verify the package profile for an owner is sorted by download count - #1796 - Zhi
- [x] Verify login, click on Admin tab, then the username - #2085 remain fixed - Zhi
- [x] Verify log in as Admin, then click the database administration link - #2140 remain fixed - Zhi
- [x] Verify the package preview Icon on Package edit page - #1455 - Dan
- [x] Verify navigate to the curated feed pagination URL and inspect the Previous/Next links at the bottom of the page - issue #2105 - Dan
- [ ] Verify adding a new package to a curated feed works (need to be a feed manager) - #2107 - Dan 
- [ ] Deploy a private gallery in a virtual directory in IIS and verify the logo on homepage looks fine - #2121 - Dan
- [x] Verify the layout/UI of the home page is not affected - issue #2167 - Zhi
- [x] Upload a new version of NuGet.Commandline package and verify that the site is not broken - issue #2168 - Dan
- [x] Verify that register a new user, go to Confirmation page and then clicking (change) wont get a 404 - issue #2176 - Dan
- [ ] Verify confirmation email is being sent after changing to a new email account - issue #2178 - Dan 
  - need to also verify it after deploying to production, as it's a config issue.
- [x] Verify changing email address to one that's already in use will not fail silently, check the error message  - issue #2181 - Dan
- [x] Verify nuget.exe delete to unlist a package owned on the gallery - issue #2190 - Dan
- [ ] Run gallery functional tests - Dan
## Test Status
1. Test is complete.
