### ISSUE TITLE
Add Functional tests for SemVer 2.0 scenarios

### ISSUE THREAD

**Issue by skofman1** [NuGet/NuGetGallery#3762]
Automate tests from: https://github.com/NuGet/NuGetGallery/issues/3731

Steps:

- [x] Add new project for end-to-end tests: https://github.com/NuGet/NuGetGallery/issues/3785
- [x] End-to-end tests for CRUD on SemVer 2.0.0 packages: https://github.com/NuGet/NuGetGallery/issues/3786
- [x] End-to-end tests for SemVer 2.0.0 filtering: https://github.com/NuGet/NuGetGallery/issues/3787
- [x] End-to-end tests for client integration (different versions of nuget.exe): https://github.com/NuGet/NuGetGallery/issues/3788
