### ISSUE TITLE
SemVer2 Deployment

### ISSUE THREAD

**Issue by xavierdecoster** [NuGet/NuGetGallery#4027]
V3 Deployment Remaining work.
* [x] Create new Lucene index for SemVer 2.0.0 (using db2lucene) #3756
* [x] Verify that SemVer2 aware registration blobs for prod have been created. If they have not, create these, (approx 5 hours when split into 2 jobs according to @joelverhagen 's last timing). https://github.com/NuGet/NuGetGallery/issues/3683
* [x] Deploy a new catalog2registration job that updates all three containers (ie, there will be one job that writes updates to reg1, reg1-gz, and reg2).
* [x] Redeploy search service and update semVer2RegistrationBaseAddress variable to point to SemVer2 Registration. SemVer 2.0.0 search service should use SemVer 2.0.0 registration URLs #3743  
* [x] Update v3/index.json to mention the new SemVer 2.0.0 registration hive #3684

Gallery Deployment Remaining Work
* [x] FI Merge from NuGetGallery master into dev https://github.com/NuGet/NuGetGallery/pull/4030
* [x] Merge https://github.com/NuGet/NuGetGallery/pull/4031 into semver2 feature branch
* [x] Merge SemVer feature branch into dev
* [x] Merge dev-nuget430 shims branch into dev
* [x] Update version to `4.3.0`
* [x] Test deploy DEV gallery branch to DEV environment using DEV shims branch
* [x] run EF Migrations on DEV
* [x] Merge dev branch into master for NuGetGallery
* [x] Merge dev shims branch to master
* [x] Test deploy MASTER gallery branch to DEV environment using MASTER shims branch
* [x] set SemVerLevel=2 for semver2 package versions on DEV
* [x] deploy Gallery to DEV and run all tests
* [x] run EF Migrations on INT
* [x] set SemVerLevel=2 for semver2 package versions on INT
* [x] deploy Gallery to INT and run all tests
* [x] run EF Migrations on PROD
* [x] set SemVerLevel=2 for semver2 package versions on PROD
* [x] deploy Gallery to PROD and run all tests
* [x] promote deployment of Gallery to secondary PROD environment

**Comment by skofman1** [comment]
A few questions:
- Regarding V3 catalog2registration job to update SemVer 2.0 container - I was under the impression we only need one job to update all containers.
- Shims work - perhaps it's part of the plan and just not written: you can test the Shims integration locally without deployment to DEV as a sanity check. Instructions are in OneNote: https://microsoft.sharepoint.com/teams/NuGet/_layouts/OneNote.aspx?id=%2Fteams%2FNuGet%2FTeam%2FNugetServer%2FNugetServerTeamNote&wd=target%28QA.one%7CE377F191-30A2-46CE-9869-A187F139EB06%2FRunning%20Gallery%20with%20Shims%7C32FD4B99-51F8-4CE4-9E89-E649C18A21B1%2F%29
onenote:https://microsoft.sharepoint.com/teams/NuGet/Team/NugetServer/NugetServerTeamNote/QA.one#Running%20Gallery%20with%20Shims&section-id={E377F191-30A2-46CE-9869-A187F139EB06}&page-id={32FD4B99-51F8-4CE4-9E89-E649C18A21B1}&object-id={CBC820D0-5041-0DFF-2A2E-90AA2858E1C8}&2B

**Comment by ryuyu** [comment]
You are correct. we just have to point it to all containers. I'll update the step.

**Comment by xavierdecoster** [comment]
shims work: i know :) just need it merged in the right order, been using those shims for weeks now, they work fine ^^
