### ISSUE TITLE
Services and NuGet.org support for Package Vulnerability Audit (PVA)

### ISSUE THREAD

**Issue by anangaur** [NuGet/NuGetGallery#7132]
This issue tracks the Gallery side of work to enable the feature: [Security] Flag vulnerable packages [#8087](https://github.com/NuGet/Home/issues/8087).

# Recently Triaged Issues

All issues in this section should be triaged by the v-team into one of their business objectives or features.

- [ ] https://github.com/NuGet/Engineering/issues/2850
- [ ] https://github.com/NuGet/NuGetGallery/issues/8407
- [ ] https://github.com/NuGet/NuGetGallery/issues/8826

**Comment by rrelyea** [comment]
Besides the nuget home issue, is there more published for this feature yet? Can we provide a link, if so?
cc @zjrunner

**Comment by anangaur** [comment]
Linked the [spec](https://github.com/NuGet/Home/wiki/Flag-vulnerable-packages) from the [Home issue](https://github.com/NuGet/Home/issues/8087), as well.

**Comment by drewgillies** [comment]
Closing this epic--future fixes and feature work can be tracked separately. /cc @anangaur

**Comment by drewgillies** [comment]
Second thoughts. Re-opening as these remaining pieces are important to continue tracking as part of the epic.
