### ISSUE TITLE
[A11y] Address display package page accessibility bugs

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#8790]
Internal work items:

* [x] [#1384208](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1384208) - Add label to installation instructions link
* [x] [#1384850](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1384850) - Package manager drop down, no longer needed
* [x] [#1384910](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1384910) - Bootstrap 3 tabs are announced twice. Does not repro on Bootstrap 4. 
* [x] [#1384927](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1384927) - Bootstrap 3 claims unselected tabs are selected. Does not repro on Bootstrap 4
* [x] [#1384936](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1384936) - Adding text spacing breaks Used by tab
* [ ] ~~[#1385790](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1385790) - Copied button not announced~~. Moved to: https://github.com/NuGet/NuGetGallery/issues/8809

Then update accessibility conformance documentation: [#1385846](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1385846)

**Comment by loic-sharma** [comment]
Bug [#1385790](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1385790) was moved to https://github.com/NuGet/NuGetGallery/issues/8809 as the issue regressed again. All other bugs were confirmed as fixed by the accessibility team. Closing this work item
